### ISSUE TITLE
Bug: Multiple "backup" folders in device backups.

### ISSUE THREAD

**Issue by Aterfax** [uroni/urbackup-client-docker#5]
https://github.com/uroni/urbackup-client-docker/blob/d27dd5f4ea178c38e19942c001d4908bf9abbdcd/entrypoint.sh#L29

I think this might be related? Not sure! In any case I have seen each device backing up using this container reflect more and more "backup_X" folders over time.

![image](https://github.com/uroni/urbackup-client-docker/assets/8648058/cf2a3f20-b218-48d8-bc0e-981039d766a8)

**Comment by laurentlemercier** [comment]
I think I understood the root cause of this : each time the container is restarted, the entry point adds a new backup entry to the list.

Example after first restart : 
```
root@31649aefa413:/# urbackupclientctl list-backupdirs
PATH    NAME     FLAGS                                          
------- -------- ---------------------------------------------- 
/backup backup   follow_symlinks,symlinks_optional,share_hashes 
/backup backup_0 follow_symlinks,symlinks_optional,share_hashes 

```
@uroni : Need to add a test before adding (urbackupclientctl add -d "$dir") , something like (tested in a container shell) : 
```
                if (  urbackupclientctl list-backupdirs | grep -q "No directories are being backed up" ) ; then
                       echo "Backing up volume $dir"
                       urbackupclientctl add -d "$dir"
                else
                        if ! ( urbackupclientctl list-backupdirs | tail  --lines=+3 | grep -q "$dir"  ); then
                                echo "Backing up volume $dir"
                                urbackupclientctl add -d "$dir"
                        fi
                fi
```

thanks in advance 

Laurent
P.S: PR https://github.com/uroni/urbackup-client-docker/pull/6 opened for it
